package com.xuhui.projecthou;

import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.RequestMethod;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn

@SpringBootApplication
@MapperScan("com.xuhui.projecthou.dao")
@CrossOrigin(origins = {"http://uzixuhui.com"},methods = {RequestMethod.DELETE})
public class ProjectHouApplication {

    public static void main(String[] args) {
        SpringApplication.run(ProjectHouApplication.class, args);
    }

}
